# Generated by Django 6.0.3 on 2026-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('qurilish', 'Construction and repair'), ('yuk_tashish', 'Moving and delivery'), ('tozalash', 'Cleaning service'), ('qishloq', 'Agriculture'), ('savdo', 'Retail and services'), ('it', 'IT and computers'), ("ta'lim", 'Education and tutoring'), ("sog'liqni_saqlash", 'Healthcare'), ('cafe', 'Cafe and restaurant'), ('boshqa', 'Other')], default='boshqa', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(choices=[('toshkent_shahar', 'Tashkent city'), ('toshkent_viloyat', 'Tashkent region'), ('andijon', 'Andijan region'), ('fargona', 'Fergana region'), ('namangan', 'Namangan region'), ('samarqand', 'Samarkand region'), ('buxoro', 'Bukhara region'), ('qashqadaryo', 'Kashkadarya region'), ('surxondaryo', 'Surkhandarya region'), ('jizzax', 'Jizzakh region'), ('sirdaryo', 'Syrdarya region'), ('navoiy', 'Navoi region'), ('xorazm', 'Khorezm region'), ('qoraqalpogiston', 'Republic of Karakalpakstan')], default='toshkent_shahar', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=0, help_text='In UZS', max_digits=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('kunlik', 'Daily'), ('soatlik', 'Hourly'), ('loyiha', 'Project')], default='kunlik', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ochiq', 'Open'), ('yopiq', 'Closed'), ('tugallangan', 'Completed')], default='ochiq', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Pending'), ('qabul_qilindi', 'Accepted'), ('rad_etildi', 'Rejected')], default='kutilmoqda', max_length=20),
        ),
    ]
