# Generated by Django 6.0.3 on 2026-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('toshkent_shahar', 'Tashkent city'), ('toshkent_viloyat', 'Tashkent region'), ('andijon', 'Andijan region'), ('fargona', 'Fergana region'), ('namangan', 'Namangan region'), ('samarqand', 'Samarkand region'), ('buxoro', 'Bukhara region'), ('qashqadaryo', 'Kashkadarya region'), ('surxondaryo', 'Surkhandarya region'), ('jizzax', 'Jizzakh region'), ('sirdaryo', 'Syrdarya region'), ('navoiy', 'Navoi region'), ('xorazm', 'Khorezm region'), ('qoraqalpogiston', 'Republic of Karakalpakstan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('employer', 'Employer')], default='worker', max_length=20),
        ),
    ]
